FROM public.ecr.aws/docker/library/mysql:8.0

ENV MYSQL_DATABASE=employees
ENV MYSQL_ROOT_PASSWORD=db_pass123

# initialize DB from this script at container start
COPY mysql.sql /docker-entrypoint-initdb.d/mysql.sql
